{"name": "Проверка появления ошибки при авторизации курьера с неверным полем login", "status": "passed", "description": "Создание курьера и его авторизация с неверным полем login, проверка статуса ответа с ошибкой и теста ошибки в ответе", "start": 1715362817603, "stop": 1715362817922, "uuid": "9b479d85-413c-4e4d-ab73-e897256de6e8", "historyId": "8ac916f26d9a725182f896817b8d725e", "testCaseId": "8ac916f26d9a725182f896817b8d725e", "fullName": "tests.test_login_courier.TestLoginCourier#test_fail_with_wrong_login", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_courier"}, {"name": "subSuite", "value": "TestLoginCourier"}, {"name": "host", "value": "LAPTOP-DIB55KQC"}, {"name": "thread", "value": "10444-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_courier"}]}